# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/calma/Workspace/personal/chip8_emulator/chip8_emulator.srcs/sources_1/bd/video_out/ip/video_out_v_axi4s_vid_out_0_1/video_out_v_axi4s_vid_out_0_1.xci
# IP: The module: 'video_out_v_axi4s_vid_out_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/calma/Workspace/personal/chip8_emulator/chip8_emulator.gen/sources_1/bd/video_out/ip/video_out_v_axi4s_vid_out_0_1/video_out_v_axi4s_vid_out_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_out_v_axi4s_vid_out_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/calma/Workspace/personal/chip8_emulator/chip8_emulator.gen/sources_1/bd/video_out/ip/video_out_v_axi4s_vid_out_0_1/video_out_v_axi4s_vid_out_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_out_v_axi4s_vid_out_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/calma/Workspace/personal/chip8_emulator/chip8_emulator.srcs/sources_1/bd/video_out/ip/video_out_v_axi4s_vid_out_0_1/video_out_v_axi4s_vid_out_0_1.xci
# IP: The module: 'video_out_v_axi4s_vid_out_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/calma/Workspace/personal/chip8_emulator/chip8_emulator.gen/sources_1/bd/video_out/ip/video_out_v_axi4s_vid_out_0_1/video_out_v_axi4s_vid_out_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_out_v_axi4s_vid_out_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/calma/Workspace/personal/chip8_emulator/chip8_emulator.gen/sources_1/bd/video_out/ip/video_out_v_axi4s_vid_out_0_1/video_out_v_axi4s_vid_out_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_out_v_axi4s_vid_out_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
