# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/video_out/video_out.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==video_out || ORIG_REF_NAME==video_out} -quiet] -quiet

# IP: bd/video_out/ip/video_out_v_tc_0_0/video_out_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==video_out_v_tc_0_0 || ORIG_REF_NAME==video_out_v_tc_0_0} -quiet] -quiet

# IP: bd/video_out/ip/video_out_v_axi4s_vid_out_0_1/video_out_v_axi4s_vid_out_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==video_out_v_axi4s_vid_out_0_1 || ORIG_REF_NAME==video_out_v_axi4s_vid_out_0_1} -quiet] -quiet

# IP: bd/video_out/ip/video_out_clk_wiz_0/video_out_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==video_out_clk_wiz_0 || ORIG_REF_NAME==video_out_clk_wiz_0} -quiet] -quiet

# IP: bd/video_out/ip/video_out_rst_clk_wiz_74M_0/video_out_rst_clk_wiz_74M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==video_out_rst_clk_wiz_74M_0 || ORIG_REF_NAME==video_out_rst_clk_wiz_74M_0} -quiet] -quiet

# IP: bd/video_out/ip/video_out_axis_subset_converter_0_0/video_out_axis_subset_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==video_out_axis_subset_converter_0_0 || ORIG_REF_NAME==video_out_axis_subset_converter_0_0} -quiet] -quiet

# XDC: /home/calma/Workspace/personal/chip8_emulator/chip8_emulator.gen/sources_1/bd/video_out/video_out_ooc.xdc
