#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Jul 30 22:09:02 EDT 2025
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail

# resolve compiled library path in xsim.ini
export RDI_DATADIR="/tools/Xilinx/Vivado/2024.2/data"

# elaborate design
echo "xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L axi_lite_ipif_v3_0_4 -L v_tc_v6_2_9 -L v_tc_v6_1_14 -L v_vid_in_axi4s_v4_0_11 -L v_axi4s_vid_out_v4_0_19 -L lib_cdc_v1_0_3 -L proc_sys_reset_v5_0_16 -L axis_infrastructure_v1_1_1 -L axis_register_slice_v1_1_33 -L axis_subset_converter_v1_1_33 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot system_behav xil_defaultlib.system xil_defaultlib.glbl -log elaborate.log"
xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L axi_lite_ipif_v3_0_4 -L v_tc_v6_2_9 -L v_tc_v6_1_14 -L v_vid_in_axi4s_v4_0_11 -L v_axi4s_vid_out_v4_0_19 -L lib_cdc_v1_0_3 -L proc_sys_reset_v5_0_16 -L axis_infrastructure_v1_1_1 -L axis_register_slice_v1_1_33 -L axis_subset_converter_v1_1_33 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot system_behav xil_defaultlib.system xil_defaultlib.glbl -log elaborate.log

